# frozen_string_literal: true
gem 'apir', :git => 'git://github.com/xenjke/apir.git'

source 'https://rubygems.org'
gem 'activesupport'
gem 'allure-rspec', '~> 0.6.9'
gem 'capybara'
gem 'capybara-mechanize'
gem 'capybara-webkit'
gem 'colorize'
gem 'faker'
gem 'fuubar'
gem 'gmail'
gem 'hashdiff'
gem 'json-schema'
gem 'mysql2'
gem 'net-sftp'
gem 'net-ssh', '~> 3.0.0'
gem 'nokogiri', '1.6.8'
gem 'nyan-cat-formatter'
gem 'parallel_tests'
gem 'pdf-reader'
gem 'phantomjs', :require => 'phantomjs/poltergeist'
gem 'poltergeist'
gem 'pry'
gem 'rainbow', '2.1.0'
gem 'rake'
gem 'rest-client'
gem 'rspec'
gem 'rspec_junit_formatter'
gem 'rubocop', require: false
gem 'rubyzip', '>= 1.0.0'
gem 'sequel'
gem 'sucker_punch'
gem 'timers'
gem 'timezone', '~> 1.0'
gem 'tty-command'
gem 'unicode'
gem 'yard'
